# Generated by Django 5.1.3 on 2025-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnick_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="landing_airport",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="flight",
            name="takes_off_airport",
            field=models.CharField(max_length=100),
        ),
    ]
